# SeleniumProjectsSundar1
Amozon login

package pratice;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Amozonlogin {

	public static void main(String[] args) {
		WebDriver d=new ChromeDriver();
		d.get("https://www.facebook.com/login.php");
        d.findElement(By.id("email")).sendKeys("6382518651");
        d.findElement(By.id("pass")).sendKeys("Sundar");
        d.findElement(By.name("login")).click();
	}
	
	

}
